import { api } from "./client";

export interface Asset {
  _id: string;
  projectId: string;
  roomId?: string | null;
  fileName: string;
  fileType: string;
  fileSize: number;
  s3Key: string;
  url: string; // This will hold the signed URL generated by backend
  createdAt: string;
  updatedAt: string;
}

export const getAssets = async (projectId: string, roomId?: string | null) => {
  const params: Record<string, string> = { projectId };
  if (roomId !== undefined) {
    params.roomId = roomId || "null";
  }
  const response = await api.get<Asset[]>("/assets", { params });
  return response.data;
};

export const uploadAsset = async (formData: FormData) => {
  const response = await api.post<Asset>("/assets/upload", formData, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });
  return response.data;
};

export const deleteAsset = async (id: string) => {
  await api.delete(`/assets/${id}`);
};
